<?php
/**
 * Created by PhpStorm.
 * User: samsung
 * Date: 26.11.2015
 * Time: 21:04
 */

namespace indexTest;


require '../index.php';

use index\Index;
//use index;

class indexTest extends \PHPUnit_Framework_TestCase
{

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

    }

    public $index;

    public function testAdd(){

        $this->index = new Index();

        $this->assertEquals(4,$this->index->add(2,2));

    }

}
